config/routes.rb
SimpleMenu::Application.routes.draw do

  resources :food_items


  resources :food_tests

  resources :food_items

  devise_for :users

  post ":controller/:id" => ":controller#update" #workaround for UJS form_for not working with PUT requests, required for index scaffolding
  post "versions/:id/revert" => 'versions#revert', :as => 'revert_version' #paper trail ajax controller, required for scaffolding

  root to: 'food_tests#index'
end

app/views/shared/_alert_box.html.haml
.alert.fade.in{class: (local_assigns[:class] ||= 'alert-success')}
    %a.close{data: {dismiss: 'alert'}, aria: {hidden: true}, href: '#'} &times;
    %strong= text

app/views/shared/_combo_partial.html.haml
-#render multiple partials via an array of partial names. Partials will be siblings in document.
-# Params:
-# partials(hash): Object of the form {name:string, locals:hash}

- partials.each do |partial|
  = render partial: "#{partial[:name]}", locals: partial[:locals]

app/views/shared/_help_block.html.haml
-#Params:
  is_error(boolean): if true will display exclamation icon
  text(string): text to use for help block

%p.help-block{style: (is_error ||= false) ? 'color:#d43f3a;' : 'color: #333333' }
  %span.glyphicon{ class: (is_error ? 'glyphicon-exclamation-sign' : 'glyphicon-info-sign')}
  %strong= text

app/views/shared/_index_page_control.html.haml
-# params: pages
.row
  %div{style: 'text-align:center;'}
    %h4#page-number-label Page 1
.row
  %div{style: 'text-align:center;'}
    .pagination-control-group.btn-group
      - if pages > 10
        %button#first-page.btn.btn-default.btn-sm{title: 'First Page'}
          %span.glyphicon.glyphicon-step-backward

        %button#prev-page.btn.btn-default.btn-sm{title: 'Previous Page'}
          %span.glyphicon.glyphicon-chevron-left

        %button#next-page.btn.btn-default.btn-sm{title: 'Next Page'}
          %span.glyphicon.glyphicon-chevron-right

        %button#last-page.btn.btn-default.btn-sm{title: 'Last Page'}
          %span.glyphicon.glyphicon-step-forward
      - else
        - (1..(pages < 1 ? 1 : pages)).each do |pg|
          %button.btn.btn-default.btn-sm.individual-pg-control{data: {page: pg - 1}}
            %b= "#{pg}"

app/views/shared/_new_model_toolbar.html.haml
-# index page toolbar for a new/edit model. Param is model
.btn-group
  -# save
  %button.btn.btn-primary{title: 'Save', type: 'submit'}
    %span.glyphicon.glyphicon-floppy-disk

  -# clear
  %a.clear-input.btn.btn-danger{title: 'Clear fields'}
    %span.glyphicon.glyphicon-remove

  -# cancel editing
  - unless model.new_record?
    = link_to model, remote: true, class: 'btn btn-default cancel-edit', title: 'Cancel Edit', data: {type: 'html'} do
      %span.glyphicon.glyphicon-share-alt

app/views/shared/_rud_toolbar.html.haml
-# toolbar for ActiveRecord instance
-#model: activerecord model instance with RUD controller methods
-#[enabled_buttons] = {show:(bool = (can? :read, model)), edit:(bool = (can? :update, model)), destroy:(bool = (can? :destroy, model))}

.btn-group
  -#show
  - if enabled_buttons[:show] ||= (can? :read, model)
    = link_to model, class: 'btn btn-default', title:'Show' do
      %span.glyphicon.glyphicon-eye-open

  -#edit
  - if enabled_buttons[:edit] ||= (can? :update, model)
    = link_to edit_polymorphic_path(model), remote: true, class: 'btn btn-default row-edit', title: 'Edit', data: {type: 'html'} do
      %span.glyphicon.glyphicon-edit

  -#destroy
  - if enabled_buttons[:destroy] ||= (can? :destroy, model)
    = link_to model, method: :delete, confirm: "Will delete #{model.to_s}. Continue?", remote: true, class: 'btn btn-default row-destroy', title: 'Delete', data: {type: 'html'} do
      %span.glyphicon.glyphicon-trash

app/views/shared/_title.html.haml
-#optionally accepts block embedded in .row after title
.row
  .col-lg-6{style: 'margin-bottom: 1em;'}
    %h2= (title ||= "#{params[:action].titleize} #{params[:controller].singularize.titleize}")
    - if block
      = block

app/views/shared/_undo_button.html.haml
-#params: version_id
.btn-group
  = link_to revert_version_path(version_id), method: :post, remote: true, class: 'btn btn-danger', title: 'Undo Delete', data: {type: 'html'} do
    %span.glyphicon.glyphicon-share-alt
  %a.btn.btn-danger.remove-row{title: 'Remove Row'}
    %span.glyphicon.glyphicon-minus